Some fixes and add User and Group API support
pwelch/virustotal_api pull request #31
Opened 2020-10-06 15:17 UTC by jonnynux

* Fix Fix exists? check
* Fix detected_by for File
* Fix RateLimitError
* Added User and Group API

2020-10-06 15:42 UTC, crondaemon requested changes

2020-10-06 15:42 UTC, crondaemon commented on test/group_test.rb
> +      vturl_report = VirustotalAPI::Group.find(@group_id, @api_key)
vturl_report?

2020-10-06 15:42 UTC, crondaemon commented on test/user_test.rb
> +      vturl_report = VirustotalAPI::User.find(@api_key, @api_key)
Same here.

2020-10-06 15:42 UTC, crondaemon commented on lib/virustotal_api/base.rb
> +      !!report
What's the deal with the former code? The commit message doesn't really explain why is was buggy and how the new code fixes it.

2020-10-07 09:52 UTC, crondaemon commented
LGTM.

2020-10-08 07:51 UTC, jonnynux commented
Hi @pwelch, have you had the opportunity to look at this?

Thanks ;)

2020-10-08 11:14 UTC, pwelch commented
@jonnynux Looks good to me! 

Should this be cut as a new version or did you have more changes you wanted to roll into the next release?

2020-10-08 11:14 UTC, pwelch approved these changes
👍

2020-10-08 13:23 UTC, jonnynux commented
> 
> 
> @jonnynux Looks good to me!
> 
> Should this be cut as a new version or did you have more changes you wanted to roll into the next release?

Yes, new version. At the moment this is enough. I added a commit with the 0.5.2 version, but feel free to edit it as you want.

2020-10-08 13:56 UTC, pwelch commented
> > @jonnynux Looks good to me!
> > Should this be cut as a new version or did you have more changes you wanted to roll into the next release?
> 
> Yes, new version. At the moment this is enough. I added a commit with the 0.5.2 version, but feel free to edit it as you want.

Sounds good! I'll Publish it today.

2020-10-08 13:57 UTC, merged

2020-10-08 14:06 UTC, pwelch commented
@jonnynux & @crondaemon 

Released v0.5.2: https://rubygems.org/gems/virustotal_api

2020-10-08 14:11 UTC, crondaemon commented
:+1: thanks, appreciate.

2020-10-08 15:51 UTC, jonnynux commented
Thanks